eureka:
  client:
    enabled: true
    service-url:
      defaultZone: http://127.0.0.1:8761/eureka/
    register-with-eureka: true
    fetch-registry: true
  instance:
    hostname: 127.0.0.1
spring:
  application:
    name: eureka-provider
server:
  port: 8081
feign:
  client:
    config:
      default:
        read-timeout: 30000
        connect-timeout: 30000
