server:
  port: 8081


spring:
  application:
    name: Admin Client
  boot:
    admin:
      client:
        url: http://127.0.0.1:8080
management:
  endpoints:
    web:
      exposure:
        include: "*"
