# https://github.com/alibaba/druid/wiki/DruidDataSource配置
ahao:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    master-bean-name: masterDataSource
    salve-bean-name: slave1DataSource,slave2DataSource

    master:
      username: root
      password: root
      url: jdbc:mysql://172.20.2.135:3306/my_db1?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false


      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      #filters: stat

      # 配置初始化大小、最小、最大
      maxActive: 20
      initialSize: 5
      maxWait: 60000  # 配置获取连接等待超时的时间
      minIdle: 10

      timeBetweenEvictionRunsMillis: 2000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 600000  # 配置一个连接在池中最小生存的时间，单位是毫秒
      #      maxEvictableIdleTimeMillis: 900000  # 配置一个连接在池中最大生存的时间，单位是毫秒

      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false

      keepAlive: true
      phyMaxUseCount: 100000

      poolPreparedStatements: true    # 打开PSCache，并且指定每个连接上PSCache的大小
      maxPoolPreparedStatementPerConnectionSize: 20

      asyncInit: true   # asyncInit是1.1.4中新增加的配置，如果有initialSize数量较多时，打开会加快应用启动时间
    slave1:
      username: root
      password: root
      url: jdbc:mysql://172.20.2.135:3306/my_db2?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false


      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      #filters: stat

      # 配置初始化大小、最小、最大
      maxActive: 20
      initialSize: 5
      maxWait: 60000  # 配置获取连接等待超时的时间
      minIdle: 10

      timeBetweenEvictionRunsMillis: 2000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 600000  # 配置一个连接在池中最小生存的时间，单位是毫秒
      #      maxEvictableIdleTimeMillis: 900000  # 配置一个连接在池中最大生存的时间，单位是毫秒

      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false

      keepAlive: true
      phyMaxUseCount: 100000

      poolPreparedStatements: true    # 打开PSCache，并且指定每个连接上PSCache的大小
      maxPoolPreparedStatementPerConnectionSize: 20

      asyncInit: true   # asyncInit是1.1.4中新增加的配置，如果有initialSize数量较多时，打开会加快应用启动时间
    slave2:
      username: root
      password: root
      url: jdbc:mysql://172.20.2.135:3306/my_db3?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false


      # 配置监控统计拦截的filters，去掉后监控界面sql无法统计，'wall'用于防火墙
      #filters: stat

      # 配置初始化大小、最小、最大
      maxActive: 20
      initialSize: 5
      maxWait: 60000  # 配置获取连接等待超时的时间
      minIdle: 10

      timeBetweenEvictionRunsMillis: 2000 # 配置间隔多久才进行一次检测，检测需要关闭的空闲连接，单位是毫秒
      minEvictableIdleTimeMillis: 600000  # 配置一个连接在池中最小生存的时间，单位是毫秒
      #      maxEvictableIdleTimeMillis: 900000  # 配置一个连接在池中最大生存的时间，单位是毫秒

      validationQuery: SELECT 1
      testWhileIdle: true
      testOnBorrow: false
      testOnReturn: false

      keepAlive: true
      phyMaxUseCount: 100000

      poolPreparedStatements: true    # 打开PSCache，并且指定每个连接上PSCache的大小
      maxPoolPreparedStatementPerConnectionSize: 20

      asyncInit: true   # asyncInit是1.1.4中新增加的配置，如果有initialSize数量较多时，打开会加快应用启动时间



