filebeat.inputs:
  - type: log
    enabled: true
    paths:
      - /var/log/hadoop-hdfs/lihm.log
    multiline:
      pattern: '^[0-9]{4}-[0-9]{2}-[0-9]{2}'
      negate: true
      match: after

output.kafka:
  enabled: true
  hosts: ["127.0.0.1:9092"]
  topic: test

logging.level: error
name: 100.73.12.124
