spring:
  datasource:
    druid:
      url: jdbc:mysql://127.0.0.1:3306/my_db?useUnicode=true&characterEncoding=utf8&zeroDateTimeBehavior=convertToNull&useSSL=false&nullNamePatternMatchesAll=true&allowMultiQueries=true
      username: root
      password: root
      driver-class-name: com.mysql.cj.jdbc.Driver

      # 连接测试, 会降低性能
      validation-query: select 'x' # 判断连接是否成功的 sql 语句
      validation-query-timeout: 5  # 检测连接是否有效的超时时间, 单位是毫秒
      test-on-borrow: false        # 申请连接时执行 validationQuery 检测连接是否有效
      test-on-return: false        # 归还连接时执行validationQuery检测连接是否有效
      test-while-idle: true        # 申请连接时, 如果空闲时间大于 time-between-eviction-runs-millis, 则执行 validation-query 判断连接是否有效

      stat-view-servlet:
        enabled: true
        allow: 127.0.0.1
        deny: 192.168.1.100        # deny 优先于 allow
        login-password: druid
        login-username: 12345
        reset-enable: false        # 是否能够重置数据
