spring:
  application:
    name: "Ahao-App"
  profiles:
    active: dev
  output:
    ansi:
      enabled: always
logging:
#  config: classpath:logback/logback-${spring.profiles.active}.xml
  config: classpath:log4j2/log4j2.xml
