spring:
  redis:
    host: localhost
    port: 6379
    database: 0
    password:
    timeout: 10000     # 连接超时时间（毫秒）
    jedis:
      pool:
        max-active: 8  # 连接池最大连接数（使用负值表示没有限制）
        max-wait: 1200ms # 连接池最大阻塞等待时间（使用负值表示没有限制）
        max-idle: 8    # 连接池中的最大空闲连接
        min-idle: 0    # 连接池中的最小空闲连接
        time-between-eviction-runs: -1ms # 空闲连接扫描间隔时间, 扫描到空闲连接则关闭连接


