# =================================== 内置 Tomcat 通用配置 ==========================================
server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    max-threads: 200
    max-connections: 10000
    accept-count: 100
  max-http-header-size: 8KB # 每个请求都会创建一个8KB大小的byte[], org.apache.coyote.http11.Http11InputBuffer.java:698

# =================================== Spring 通用配置 ==========================================
spring:
  application:
    name: AhaoWeb
  profiles:
    active: dev
  http:
    encoding:
      charset: UTF-8
  jackson:
    date-format: com.ahao.util.commons.lang.time.MultiDateFormat
    default-property-inclusion: non_null # 不允许输出 null 值
    time-zone: GMT+8
    serialization:
      indent_output: false
  servlet:
    multipart:
      enabled: true
      max-file-size: 1MB
      max-request-size: 10MB
      location: ${java.io.tmpdir}
  banner:
    location: classpath:banner/banner-${spring.profiles.active}.txt
  task:
    execution:
      pool:
        allow-core-thread-timeout: true
        core-size: 8
        max-size: 128
        keep-alive: 60s
      thread-name-prefix: task-
    scheduling:
      pool:
        size: 8
      thread-name-prefix: scheduling-
logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml
