# =================================== 内置 Tomcat 通用配置 ==========================================
server:
  port: 8080
  servlet:
    context-path: /
  tomcat:
    max-threads: 200
    max-connections: 10000
    accept-count: 100

# =================================== Spring 通用配置 ==========================================
spring:
  application:
    name: AhaoWeb
  profiles:
    active: dev
  http:
    encoding:
      charset: UTF-8
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    default-property-inclusion: non_null # 不允许输出 null 值
    time-zone: GMT+8
    serialization:
      indent_output: false
  banner:
    location: classpath:banner/banner-${spring.profiles.active}.txt
logging:
  config: classpath:logback/logback-${spring.profiles.active}.xml
