spring:
  application:
    name: dubbo-provider
server:
  port: 8082
dubbo:
  application:
    name: ${spring.application.name}
    qos-enable: true
    qos-port: 20001
  scan:
    base-packages: moe.ahao.spring.boot.*
  protocol:
    name: dubbo
    port: 12345
  registry:
    timeout: 10000
    # address: zookeeper://192.168.19.128:2181
    address: nacos://192.168.19.128:8848
